# Generated by Django 3.0.3 on 2020-06-16 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Informatica', 'Informatica'), ('Agronomia', 'Agronomia'), ('Biologia', 'Biologia'), ('Administracion', 'Administracion'), ('GestionEmpresarial', 'GestionEmpresarial'), ('Tics', 'Tics')], default='Informatica', max_length=50)),
                ('imagen', models.ImageField(upload_to='libros/portada')),
                ('archivo', models.FileField(upload_to='libros/archivo')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8)])),
                ('autores', models.CharField(max_length=250)),
                ('carrera', models.CharField(choices=[('Informatica', 'Informatica'), ('Agronomia', 'Agronomia'), ('Biologia', 'Biologia'), ('Administracion', 'Administracion'), ('GestionEmpresarial', 'GestionEmpresarial'), ('Tics', 'Tics')], default='Informatica', max_length=100)),
                ('tipo_doc', models.CharField(max_length=100)),
                ('nombre_doc', models.CharField(max_length=200)),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('archivo', models.FileField(upload_to='Residencia/archivos')),
            ],
        ),
        migrations.CreateModel(
            name='RevistaCientifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('portada', models.ImageField(upload_to='RevistaCientifica/portadas')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'RevistaCientifica',
                'verbose_name_plural': 'RevistaCientificas',
            },
        ),
        migrations.CreateModel(
            name='RevistaOsio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('portada', models.ImageField(upload_to='RevistaOsio/portadas')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'RevistaOsio',
                'verbose_name_plural': 'RevistasOsios',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video_home')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('matricula', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(8)])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
