# Generated by Django 3.0.3 on 2020-06-16 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='matricula',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='matricula',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
